default: &default
  adapter:  "mysql2"

  host:     <%= ENV['VELUM_DB_HOST'] || "" %>
  port:     <%= ENV['VELUM_DB_PORT'] || 0 %>
  username: <%= ENV['VELUM_DB_USERNAME'] || "root" %>
  password: <%= ENV['VELUM_DB_PASSWORD'] || "" %>
  database: <%= "velum_#{Rails.env.downcase}" %>
  encoding: utf8
  pool:     <%= ENV['VELUM_DB_POOL'] || 5 %>
<% if ENV['VELUM_DB_SOCKET'] %>
  socket:   <%= ENV['VELUM_DB_SOCKET'] %>
<% end %>

development:
  <<: *default
  database: <%= ENV['VELUM_DB_NAME'] || "velum_development" %>

test:
  <<: *default

production:
  <<: *default
